---
title: "Screw It"
format: html
---

```{r}
packages <- c(
  "flowCore",
  "cytolib",
  "flowWorkspace",
  "ncdfFlow",
  "flowViz",
  "FlowSOM",
  "ggcyto",
  "openCyto",
  "quantiseqr",
  "flowStats",
  "CytoML",
  "CATALYST",
  "flowAI",
  "diffcyt",
  "flowDensity",
  "flowMeans",
  "PeacoQC",
  "flowFP",
  "flowClean",
  "flowPeaks",
  "COMPASS",
  "SamSPECTRAL",
  "flowVS",
  "cydar",
  "flowMerge",
  "flowTrans",
  "distinct",
  "flowCut",
  "flowMatch",
  "flowBeads",
  "flowTime",
  "sccomp",
  "flowCHIC",
  "flowSpecs",
  "DepecheR",
  "treekoR",
  "flowBin",
  "MetaCyto",
  "immunoClust",
  "scDataviz",
  "cytoMEM",
  "flowPloidy",
  "plotGrouper",
  "CytoDx",
  "Sconify",
  "flowPlots",
  "GateFinder",
  "flowGate",
  "flowGraph",
  "infinityFlow",
  "cyanoFilter",
  "optimalFlow",
  "CytoGLMM",
  "scifer",
  "cytoKernel",
  "CytoPipeline",
  "censcyt",
  "flowCyBar",
  "reconsi",
  "MACSQuantifyR",
  "CytoMDS",
  "CytoPipelineGUI",
  "MAPFX",
  "spillR",
  "tidyFlowCore",
  "CyTOFpower",
  "tidytof",
  "SuperCellCyto"
)
```

```{r}
DataSnag <- function(x){
file <- x
Location <- paste0("https://bioconductor.org/packages/stats/bioc/", file, "/", file, "_2025_stats.tab")
stats <- read.table(Location, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
stats <- stats |> dplyr::mutate(package=file)
return(stats)
}
```

```{r}
Dataset <-purrr::map(.x=packages, .f=DataSnag) |> dplyr::bind_rows()

write.csv(Dataset, "data/Dataset.csv", row.names=FALSE)
```

```{r}
library(dplyr)
Flow <- Dataset |> filter(Month %in% "Nov") |> arrange(desc(Nb_of_distinct_IPs))
```


```{r}
library(ggplot2)

Plot <- ggplot(Flow , aes(x = Nb_of_distinct_IPs)) +
  geom_histogram(binwidth = 100, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Package Downloads",
       x = "Number of Downloads",
       y = "Count of Packages") +
  theme_minimal()

plotly::ggplotly(Plot)
```

```{r}
print("Hello")
```