---
title: "Cytometry in R"
format: html
---

Within Bioconductor, there are 68 packages listing flow cytometry within their biocView. The oldest extant of these, flowCore, has been part of the project for 19 years, receiving 26720 downloads from unique IPs in 2025. However, most of these packages are underutilized, with only 15 of them surpasing 4000 yearly downloads. A contributing factor to this is that within the flow cytometry community as a whole, vast majority of the analysis is conducted via manual (supervised) gating using commercial softwares (ex. FlowJo and FCSExpress) where gates around populations of interest are drawn, filtering for cells within, and repeating, resulting in hierarchies of gates enabling the isolation of cell populations of interest. 

With the emergence of spectral flow cytometry within the last decade, capable of profiling far more markers than conventional flow cytometry, and due to rapid acquisition speed enabling acquiring far more events than mass cytometry, the datasets are growing increasingly complex. If the analytical goal is to analyze all cell populations present within each sample, cutting-edge semi-supervised and unsupervised analytical methods will need to be employed, many of these residing within the Bioconductor project. 

For the regular flow cytometrist, this posses a barrier to entry, as they often have no-to-limited coding skills. While resources for those with intermediate coding experience (such as individual package vignettes and protocol papers) exist, there are limited resources focused on beginners. Given few bioinformaticians extensively work with flow cytometry data, at many institutions interested individuals are entirely on their own, and attempts end in frustration. 

To address this community need, and reduce the barrier to entry, starting in February we have been offering a free weekly "Cytometry in R" course, offered both in-person and online, aimed at flow cytometrist with no-to-little coding experience. 
The community response was outstanding, with over 1997 worldwide participants filling out the interest form, 529 participants creating GitHub accounts and forking the course repository, and averaging between 300-500 unique viewers per weekly topic. 

The course covers one topic per week, with multiple livestreams to accomodate different timezones. The course is hosted out of a GitHub repository, with the Quarto website available via GitHub pages. We have taken advantage of the Discussions page to serve as a community forum, fielding typical beginner questions ranging from installation errors, library not having been called, and mistyped function names. 

Beyond learning R, participants are covering how to use Git for Version control, Quarto for reproducible documentations, etc. 

All course materials and code are being offered under CC-BY-SA and AGPL3-0 licenses, and will remain available after course conclusion, allowing for community access and improvement in the future. 

We highlight what has worked, things we wish we had done differently, and unappreciated elements that encountered while reducing barriers to entry to a community that previously rather died than touch a command line. We hope the resources made available through the course enable wider utilization of Bioconductor flow cytometry packages, and inspire next generation of package maintainers and developers. 

