---
title: "Deprecated Cytometry Packages"
format: html
---

```{r}
library(rvest)
library(xml2)
library(dplyr)
library(stringr)
library(purrr)
```

```{r}
DeprecatedURL <- read_html("https://bioconductor.org/about/removed-packages/")
uls <- html_elements(DeprecatedURL, "ul.inline_list")
```

```{r}
DataScrapperDeprecated <- function(uls, target_version){
uls_version <- uls[
  map_lgl(uls, ~ {
    hrefs <- html_attr(html_elements(.x, "a"), "href")
    any(str_detect(hrefs, paste0("^/packages/", target_version, "/")))
  })
]

packages_321 <- map_dfr(
  uls_version,
  ~ {
    links <- html_elements(.x, "a")

    tibble(
      package = html_text(links),
      url     = html_attr(links, "href"),
      version = target_version
    )
  }
)

return(packages_321)
}
```

```{r}
Versions <- c("3.22", "3.21", "3.20", "3.19", "3.18", "3.17", "3.16", "3.15", "3.14", "3.13", "3.11",
"3.10", "3.9", "3.8", "3.7", "3.6", "3.5", "3.4", "3.1", "3.0", "2.14", "2.13", "2.12", "2.11", "2.10",
"2.9", "2.8", "2.7", "2.6", "2.5", "2.4", "2.3", "2.2", "2.1", "2.0", "1.9")
```

```{r}
DeprecatedBioconductor <- map(.x=Versions, .f=DataScrapperDeprecated, uls=uls) |> bind_rows()
write.csv(DeprecatedBioconductor, "data/DeprecatedPackages.csv", row.names=FALSE)
nrow(DeprecatedBioconductor)
```

```{r}
DeprecatedBioconductor <- DeprecatedBioconductor |> mutate(url = paste0("https://bioconductor.org", url))

PackageList <- DeprecatedBioconductor |> pull(package)
```

```{r}
DataScrapper2 <- function(data, x) {

  internal <- data %>% filter(package %in% x) %>% slice(1)
  Page <- internal %>% pull(url)
  version <- internal %>% pull(version)

  # Normalize URL before reading -------------------------------
  normalize_url <- function(urls) {
    vapply(urls, function(u) {
      if (grepl("\\.html$", u, ignore.case = TRUE)) {
        u
      } else if (grepl("\\.", u)) {
        paste0(sub("(.*)\\.[^\\.]*$", "\\1", u), ".html")
      } else {
        paste0(u, ".html")
      }
    }, character(1))
  }

  Page <- normalize_url(Page)

  # Safe read_html: returns NULL on error ----------------------
  page <- tryCatch(read_html(Page), error = function(e) NULL)

  # If the page failed, bail out now ---------------------------
  if (is.null(page)) {
    return(NULL)
  }

  text <- page %>%
    html_element("body") %>%
    html_element("main div.container") %>%
    html_text2()

  Imports <- str_extract(text, "Imports\t[^\t]+")
  imports_text <- str_remove(Imports, "^Imports\t")

  biocviews_line <- str_extract(text, "(?<=biocViews\\t).*?(?=\\t)")

  license_line <- str_extract(text, "License\t[^\t]+")
  license <- str_remove(license_line, "^License\t") %>% str_trim()

  since_line <- str_extract(text, "In Bioconductor since\t[^\t]+")
  since <- str_remove(since_line, "^In Bioconductor since\t") %>% str_trim()

  Data <- data.frame(
    package   = x,
    since     = since,
    license   = license,
    biocviews = biocviews_line,
    imports   = imports_text,
    version = version
  )

  return(Data)
}

```

```{r}
PackageList <- PackageList |> unique()
PackageList <- PackageList[!grepl("\\.", PackageList)]

Dataset <- map(.x=PackageList, data=DeprecatedBioconductor, .f=DataScrapper2)
Dataset <- compact(Dataset)
Dataset <- bind_rows(Dataset)

FlowDeprecated <- Dataset |>
  filter(str_detect(biocviews, regex("FlowCytometry", ignore_case = TRUE)))

FlowDeprecated <- FlowDeprecated |>
  filter(!str_detect(biocviews, regex("FlowCytometryData", ignore_case = TRUE)))

write.csv(FlowDeprecated, "data/Deprecated.csv", row.names=FALSE)
```